// <auto-generated />
using System;
using ManuBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManuBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212040555_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManuBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "product@company.com",
                            Name = "Product Manager",
                            PasswordHash = "$2a$11$dh4LkrvYdzPTtSFSAqqAf.RcWMkx5.lgSJfiG6k2VerH1SJpKIlae",
                            Role = "product_bom_manager"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "inventory@company.com",
                            Name = "Inventory Manager",
                            PasswordHash = "$2a$11$ij4US8J/zT/.4uWeXUMlKuDJeGVxE6r7Dp9dGdcengdbVsN.TLWH2",
                            Role = "inventory_manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "quality@company.com",
                            Name = "Quality Control",
                            PasswordHash = "$2a$11$lVL0DGUiFjDkUj.0hMrkgeW4JJT7qHzRUOH9Rx1DEasWWZ6jiXedO",
                            Role = "qc_manager"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "scheduler@company.com",
                            Name = "Production Scheduler",
                            PasswordHash = "$2a$11$2i9gK8y3rfdEHto0QxL2yOoKLHAHe2QIzGp6aMairHIK82zDsvIcK",
                            Role = "production_scheduler"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "quality1@company.com",
                            Name = "Quality Control 2",
                            PasswordHash = "$2a$11$aJ/tAXik2ZtoGxmHtRktwe4ICUOfkwKwy.M.ZEx565qvHOh1.C/ve",
                            Role = "qc_manager"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@company.com",
                            Name = "Admin",
                            PasswordHash = "$2a$11$pN8p4VghaXXrrc.Ym3zAPOBq4IwmrwL.PDPDSfGaF04esozxrTcEa",
                            Role = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
